name: Build & Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build App
    environment: Release
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install gpg
        run: brew install gnupg
      - name: Decrypt certificate and profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/scripts/secrets.sh
      - name: Setup keychain
        run: ./.github/scripts/keychain.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: Archive xcarchive
        uses: actions/upload-artifact@v3
        with:
          name: StormViewer.xcarchive
          path: build/StormViewer.xcarchive
      - name: Archive IPA
        uses: actions/upload-artifact@v3
        with:
          name: StormViewer.ipa
          path: build/StormViewer.ipa

  deploy:
    name: Deploy App
    needs: build
    environment: Release
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download IPA
        uses: actions/download-artifact@v3
        with:
          name: StormViewer.ipa
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight.sh
